name: LinkedIn Auto Post Bot

on:
  workflow_dispatch: # Cho phép bấm chạy thủ công bằng tay trên giao diện

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run LinkedIn Bot
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        MISSIVE_API_KEY: ${{ secrets.MISSIVE_API_KEY }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        python autobot_linkedin.py
    - name: Lưu ảnh chụp màn hình khi bị lỗi
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshots
        path: "*.png"
